repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: run-tests
      name: run tests
      entry: pytest tests
      language: python
      additional_dependencies: [pre-commit, pytest, requests-mock, bs4, pydantic]
      always_run: true
      pass_filenames: false